# Generated by Django 5.2.4 on 2025-07-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_restriction',
            field=models.PositiveBigIntegerField(blank=True, help_text='Возрастное ограничение для товара', null=True, verbose_name='Возрастное ограничение'),
        ),
    ]
