# Generated by Django 5.1.6 on 2025-03-02 09:45

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customer_id',
            field=models.IntegerField(default=contextlib.nullcontext),
        ),
        migrations.AlterField(
            model_name='basket',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basket',
            name='store_id',
            field=models.IntegerField(default=1),
        ),
    ]
