# Generated by Django 5.1.6 on 2025-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0002_alter_basket_customer_id_alter_basket_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='basket',
            name='store_id',
            field=models.PositiveIntegerField(),
        ),
    ]
