# Generated by Django 5.1.6 on 2025-03-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0003_remove_basket_session_id_alter_basket_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
