# Generated by Django 5.1.6 on 2025-03-17 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0004_basket_session_id_alter_basket_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Basket.basket'),
        ),
        migrations.CreateModel(
            name='SyncedDataFromProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField()),
                ('product_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'unique_together': {('store_id', 'product_id')},
            },
        ),
    ]
