# Generated by Django 5.1.6 on 2025-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0005_alter_basketitem_cart_synceddatafromproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='synceddatafromproduct',
            name='sku',
            field=models.CharField(default='undefined', max_length=100),
            preserve_default=False,
        ),
    ]
