# Generated by Django 5.1.7 on 2025-03-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0006_synceddatafromproduct_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='sku',
            field=models.CharField(default='undefined', max_length=100),
            preserve_default=False,
        ),
    ]
