# Generated by Django 5.2 on 2025-04-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0007_basketitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
