# Generated by Django 5.2.4 on 2025-07-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0008_alter_basket_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basket_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='customer_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='customer_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='session_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
